### PR TITLE
Update santhosh-tekuri/jsonschema dependency to v3

### PR DESCRIPTION
**Pull request by iaincalderfh**
v2 validation fails with a nullable time.Time field when the request body value is null.
Updating to v3 fixes the validation.  "make test" passes.

Client sends:
{
  "expiryDate": null
}

Gets response:
{
  "status": "INVALID_ARGUMENT",
  "error": "invalid argument: validation failed",
  "context": {
    "body": [
      "#/expiryDate: %!q(<nil>) is not valid \"date-time\""
    ]
  }
}

Request definition:

type Request struct {
	ExpiryDate *time.Time   `json:"expiryDate"`
}

### CODE REVIEW

**Comment by vearutop** [comment]
@iaincalderfh thank you! What do you think about upgrading to latest version (v5.0.0)?

**Comment by iaincalderfh** [comment]
I tried v5 but got some compile errors :-(

**Comment by vearutop** [comment]
Could you share a test case that was failing with v2?

**Comment by vearutop** [comment]
Let me check if upgrade to `v5` is feasible.

**Comment by iaincalderfh** [comment]
Ok thanks, I will try to provide a simple test case too

**Comment by iaincalderfh** [comment]
https://github.com/iaincalderfh/swaggest-rest-test-case

**Comment by vearutop** [comment]
Thank you for this PR, it is merged and tagged as https://github.com/swaggest/rest/releases/tag/v0.2.17.

**Comment by vearutop** [comment]
Upgrading to `v5` seems to have a noticeable negative performance impact, so I will need to check it more carefully.

**Pull request merged**
