### PR TITLE
Try goccy/go-json

### PR DESCRIPTION
**Pull request by vearutop**

### CODE REVIEW

**Comment by goccy** [comment]
Oh, the benchmark has failed....
If there is a problem my lib, I will fix it.
And I'm also interested in the benchmark results 😄

**Comment by vearutop** [comment]
I've tried to isolate the case when benchmark fails, but could not so far. The single unmarshaling passes ok. I suspect there might be an issue with reusable byte buffers under concurrency.

**Comment by vearutop** [comment]
@goccy overall looks good! 👍 

The time/op comparison is skewed due to CI performance instability, but memory pressure is consistently lower. :)

**Comment by goccy** [comment]
I'm very happy to hear the report.
However, I'm worried about the failed benchmark, so I'd like to fix it somehow ...

**Comment by vearutop** [comment]
@goccy the benchmark passes if I comment out `n < last` condition. Apparently `last` is not calculated correctly in this case.
https://github.com/goccy/go-json/blob/v0.4.2/decode_stream.go#L78
```go
func (s *stream) read() bool {
	if s.allRead {
		return false
	}
	buf := s.readBuf()
	last := len(buf) - 1
	buf[last] = nul
	n, err := s.r.Read(buf[:last])
	s.length = s.cursor + int64(n)
	if /*n < last ||*/ err == io.EOF {
		s.allRead = true
	} else if err != nil {
		return false
	}
	return true
}
```

**Comment by goccy** [comment]
Thank you for your great contribution .... ! I released your fixing as `v0.4.3`

**Comment by goccy** [comment]
Oh... Sorry, the data race issue needs to be resolved, so I will fix it as soon as possible.

**Comment by vearutop** [comment]
Interesting that this race is quite flaky, disappeared with job retry.

**Comment by goccy** [comment]
Thank you for the detail information ! I found solution of this bug ! I will fix it !

**Comment by goccy** [comment]
Maybe https://github.com/goccy/go-json/pull/126 fixes race problem .

**Comment by vearutop** [comment]
It seems it have fixed, I could not catch a race with that branch, while I can get race detected quite often on v0.4.3.

**Comment by goccy** [comment]
I have released the above fix as `v0.4.4` !

**Comment by vearutop** [comment]
Works great, thanks!

**Pull request closed without merging**
